# Generated by Django 4.1.1 on 2022-11-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_dni_user_dni_appointmentconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnostics',
        ),
    ]
